### ISSUE TITLE
到ijkplayer-windows/ijkmedia目录下执行configure命令 报错

### ISSUE THREAD

**Issue by passer2019** [harlanc/ijkplayer-windows#1]
我在这里执行报:configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."
我到处找了，都没有找到这几个文件。

**Comment by harlanc** [comment]
环境没在手边，等回去后我检查一下，有可能有文件漏了

**Comment by harlanc** [comment]
@passer2019 再试一下吧

**Comment by passer2019** [comment]
试过了，configure没有问题了，但是卡在make这里了。我用了msys1.0和msys2.0都不行。
$ make -j4
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /d/zdhsoft/sourcetree/ijkplayer-windows/ijkmedia/missing --run autoconf
configure.in:18: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.in:20: error: possibly undefined macro: AM_PROG_LIBTOOL
make: *** [configure] Error 1

我在考虑用visual studio编译。

**Comment by passer2019** [comment]
那个ffmpeg编译的是没有问题，就是编译这个出问题了。

**Comment by harlanc** [comment]
try to run "autoreconf -I" and then ./configure again

**Comment by harlanc** [comment]
有可能你的MINGW环境装的不全，有些组件没有装

**Comment by harlanc** [comment]
准备MINGW环境还是比较费事的，如果支持vistual studio最好不过了，我没有时间去弄这块。

**Comment by passer2019** [comment]
我试了，感觉工作量很大。SDL本是跨平台，被搞不是跨平台的，也是醉了

**Comment by passer2019** [comment]
我用的是MSYS 2的版本是，用它自带的安装工具安装mingw。我在msys 1.0和2.0，用vs2017编译都没有问题。

**Comment by passer2019** [comment]
看了一下，它用的SDL应该是2.0.x的版本，因为 1.2.x最新版本也是2012年了

**Comment by harlanc** [comment]
> 我在msys 1.0和2.0，用vs2017编译都没有问题。

现在没问题了？到底是有问题还是没问题？

**Comment by passer2019** [comment]
> > 我在msys 1.0和2.0，用vs2017编译都没有问题。
> 
> 现在没问题了？到底是有问题还是没问题？

我的意思是我在MSYS1.0和MSYS2.0下，用VC2017编译 ffmpeg 没有问题：）

**Comment by passer2019** [comment]
加我的QQ 1359113804
